### ISSUE TITLE
Forge port

### ISSUE THREAD

**Issue by DoigtdePOULET** [JSJBDEV/pirates#2]
Hi! I'm currently developping a modpack that took almost a year to assemble. Unfortunately, I don't have any programing skills... I'd like to know if is there a way to make your mod work on forge 47,3,5 (1.20.1).

I'm a video editor also, and can hekp you with these things as a trade of!

Best regard,
 
J-M

**Comment by JSJBDEV** [comment]
Hey there! porting to forge is not something Ive done in a while, however you might be able to use https://modrinth.com/mod/connector to allow the mod to run on forge 😄

**Comment by PickleBarbarian** [comment]
Hello, I saw this post hoping to inform you that while using the Sinytra Connector, the mod loads yet not of the blocks, mobs, items, or ships are present in the game. I hope you can find the time to make a forge port. If you have a solution for Sinytra Connector not loading the mod's assets in, I will appreciate that. thanks.

**Comment by JSJBDEV** [comment]
https://www.curseforge.com/minecraft/mc-mods/valkyrien-pirates/files/6026196 should work. not sure why entities wherent in the game for you but perhaps it was some other dependency.
